name: Tests
on:
  push:
    branches: [develop, stage, prod]
  pull_request:
    branches:
      - "**"
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # we can avoid to check the pg instance health since we had like 25 seconds before to use the database
        # options: >-
        #   --health-cmd pg_isready
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
      sqs:
        image: softwaremill/elasticmq-native
        ports:
          - 9324:9324
    env:
      STAGE: local
      DISABLE_TEST_CONTAINER: true
      DISABLE_BUNDLE_OFFLINE: true
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Tests
        run: npx vitest run --silent